[package]
name = "hubhook"
version = "0.5.0"
edition = "2021"

authors = ["sksat <sksat@arkedgespace.com>"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/arkedge/hubhook"
description = "GitHub notification manager"

[dependencies]
actix-service = "2.0.2"
actix-web = "4.2.1"
crypto-hashes = "0.10.0"
futures = "0.3.21"
hex = "0.4.3"
hmac = "0.12.1"
regex = "1.5.6"
serde = "1.0.137"
serde_json = "1.0.79"
structopt = "0.3.26"
surf = { version = "2.3.2", default-features = false, features = ["h1-client-rustls"] }
tracing = "0.1.35"
tracing-subscriber = "0.3.11"
url = { version = "2.2.2", features = ["serde"]}
