name: reviewdog / actionlint

on:
  pull_request:
    paths:
      - '.github/workflows/**'
  merge_group:

jobs:
  actionlint:
    name: actionlint with reviewdog
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.4.0

      - name: actionlint
        uses: reviewdog/action-actionlint@d290e336d5a743810aef4404f757dc862276d2ae # v1.73.4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-review
