name: reviewdog / actionlint

on:
  pull_request:
    paths:
      - '.github/workflows/**'
  merge_group:

jobs:
  actionlint:
    name: actionlint with reviewdog
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: actionlint
        uses: reviewdog/action-actionlint@v1.43.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-review
