name: build / container image

on:
  push:
    branches:
      - main
    tags:
      - v*
  pull_request:
    paths:
      - 'Dockerfile'
      - '.dockerignore'
      - '.github/workflows/build-image.yml'
  merge_group:

permissions:
  id-token: write
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v5
      with:
        tags: |
          type=semver,pattern={{version}}
          type=ref,event=branch
          type=ref,event=pr
          type=sha
        images: ${{ secrets.ECR_URL }}/${{ github.repository }}

    - name: Set up Buildx
      uses: docker/setup-buildx-action@v2

    - name: configure aws credentials
      uses: aws-actions/configure-aws-credentials@master
      with:
        role-to-assume: ${{ secrets.IAM_ROLE }}
        aws-region: ap-northeast-1
    - name: Login to Amazon ECR
      uses: docker/login-action@v2
      with:
        registry: ${{ secrets.ECR_URL }}

    - name: Build and Push
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
