name: reviewdog / hadolint

on:
  pull_request:
    paths:
      - Dockerfile
      - .github/workflows/hadolint.yml
  merge_group:

jobs:
  hadolint:
    name: hadolint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: hadolint
        uses: reviewdog/action-hadolint@fc7ee4a9f71e521bc43e370819247b70e5327540 # v1.50.2
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review
