name: Rust

on:
  push:
    branches:
      - main
    tags:
      - v*
  pull_request:
  merge_group:

env:
  CARGO_INCREMENTAL: 0

jobs:
  rust:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Get Rust toolchain
        id: toolchain
        run: |
          awk -F'[ ="]+' '$1 == "channel" { print "toolchain=" $2 }' rust-toolchain >> "$GITHUB_OUTPUT"

      - uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: ${{ steps.toolchain.outputs.toolchain }}
          components: clippy

      - name: cache dependencies
        uses: Swatinem/rust-cache@v2.4.0

      - name: reviewdog / clippy
        uses: sksat/action-clippy@v0.2.1
        with:
          reporter: github-pr-review

      - name: unit test
        run: |
          cargo test
