name: Rust

on:
  push:
    branches:
      - main
    tags:
      - v*
  pull_request:
  merge_group:

env:
  CARGO_INCREMENTAL: 0

jobs:
  rust:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions-rs/toolchain@v1.0.7
        with:
          toolchain: stable
          components: clippy
          override: true

      - name: cache dependencies
        uses: Swatinem/rust-cache@v2.2.0

      - name: reviewdog / clippy
        uses: sksat/action-clippy@v0.1.0
        with:
          reporter: github-pr-review

      - name: unit test
        uses: actions-rs/cargo@v1.0.3
        with:
          command: test
